from __future__ import annotations

from dataclasses import dataclass
from typing import Iterable, List


@dataclass(frozen=True)
class MetricSpec:
    name: str
    location: str
    interpretation: str
    applicability: str  # event_outcome | binary_directional | both
    layer: str  # training | learning | meta | decision | execution | economics | artifact
    label_space: str  # side | meta | trade | run | artifact
    legacy: bool = False
    primary_debug_metric: bool = True
    notes: str = ""


METRIC_SPECS: tuple[MetricSpec, ...] = (
    MetricSpec(
        name="train/loss",
        location="trainer",
        interpretation="Mean training loss over minibatches for the current epoch.",
        applicability="both",
        layer="training",
        label_space="side",
    ),
    MetricSpec(
        name="train/eval_loss",
        location="trainer",
        interpretation="Mean loss on the train-eval loader, aligned with the current model label space.",
        applicability="both",
        layer="training",
        label_space="side",
    ),
    MetricSpec(
        name="val/loss",
        location="trainer",
        interpretation="Mean validation loss in the side-model label space.",
        applicability="both",
        layer="training",
        label_space="side",
    ),
    MetricSpec(
        name="test/loss",
        location="trainer",
        interpretation="Mean test loss in the side-model label space.",
        applicability="both",
        layer="training",
        label_space="side",
    ),
    MetricSpec(
        name="{split}/accuracy",
        location="classification_metrics -> evaluator",
        interpretation="Overall side-model accuracy before meta-label filtering and trade abstention.",
        applicability="both",
        layer="learning",
        label_space="side",
        notes="Alias of {split}/cls/accuracy kept for flat dashboards.",
    ),
    MetricSpec(
        name="{split}/precision_macro",
        location="classification_metrics -> evaluator",
        interpretation="Macro precision in the side-model label space before meta filtering.",
        applicability="both",
        layer="learning",
        label_space="side",
    ),
    MetricSpec(
        name="{split}/recall_macro",
        location="classification_metrics -> evaluator",
        interpretation="Macro recall in the side-model label space before meta filtering.",
        applicability="both",
        layer="learning",
        label_space="side",
    ),
    MetricSpec(
        name="{split}/f1_macro",
        location="classification_metrics -> evaluator",
        interpretation="Macro F1 in the side-model label space before meta filtering.",
        applicability="both",
        layer="learning",
        label_space="side",
        notes="Alias of {split}/cls/f1_macro kept for flat dashboards.",
    ),
    MetricSpec(
        name="{split}/precision_class_{label}",
        location="classification_metrics -> evaluator",
        interpretation="Per-class precision in the side-model label space before meta filtering.",
        applicability="both",
        layer="learning",
        label_space="side",
    ),
    MetricSpec(
        name="{split}/recall_class_{label}",
        location="classification_metrics -> evaluator",
        interpretation="Per-class recall in the side-model label space before meta filtering.",
        applicability="both",
        layer="learning",
        label_space="side",
    ),
    MetricSpec(
        name="{split}/f1_class_{label}",
        location="classification_metrics -> evaluator",
        interpretation="Per-class F1 in the side-model label space before meta filtering.",
        applicability="both",
        layer="learning",
        label_space="side",
    ),
    MetricSpec(
        name="{split}/support_class_{label}",
        location="classification_metrics -> evaluator",
        interpretation="Count of true samples for a side-model class on the split.",
        applicability="both",
        layer="learning",
        label_space="side",
    ),
    MetricSpec(
        name="{split}/y_true_count_class_{label}",
        location="classification_metrics -> evaluator",
        interpretation="Count of true labels for a side-model class on the split.",
        applicability="both",
        layer="learning",
        label_space="side",
    ),
    MetricSpec(
        name="{split}/y_pred_count_class_{label}",
        location="classification_metrics -> evaluator",
        interpretation="Count of predicted labels for a side-model class on the split.",
        applicability="both",
        layer="learning",
        label_space="side",
    ),
    MetricSpec(
        name="{split}/y_true_pct_class_{label}",
        location="classification_metrics -> evaluator",
        interpretation="Share of true labels assigned to a side-model class on the split.",
        applicability="both",
        layer="learning",
        label_space="side",
    ),
    MetricSpec(
        name="{split}/y_pred_pct_class_{label}",
        location="classification_metrics -> evaluator",
        interpretation="Share of predictions assigned to a side-model class on the split.",
        applicability="both",
        layer="learning",
        label_space="side",
    ),
    MetricSpec(
        name="{split}/cls/*",
        location="evaluator aliases",
        interpretation="Stable namespace for all pre-meta side-classification metrics.",
        applicability="both",
        layer="learning",
        label_space="side",
        notes="Preferred namespace for learning dashboards and confusion-matrix interpretation.",
    ),
    MetricSpec(
        name="{split}/prediction_confidence_mean",
        location="evaluator",
        interpretation="Mean argmax confidence of the side model before meta filtering.",
        applicability="both",
        layer="learning",
        label_space="side",
    ),
    MetricSpec(
        name="{split}/prediction_confidence_median",
        location="evaluator",
        interpretation="Median argmax confidence of the side model before meta filtering.",
        applicability="both",
        layer="learning",
        label_space="side",
    ),
    MetricSpec(
        name="{split}/meta/accept_threshold",
        location="evaluator",
        interpretation="Meta-label probability threshold for accepting a proposed trade.",
        applicability="event_outcome",
        layer="meta",
        label_space="meta",
        notes="This is the threshold actually used by the current side-plus-meta pipeline.",
    ),
    MetricSpec(
        name="{split}/meta/precision",
        location="evaluator",
        interpretation="Meta-label precision for the TAKE class.",
        applicability="event_outcome",
        layer="meta",
        label_space="meta",
    ),
    MetricSpec(
        name="{split}/meta/recall",
        location="evaluator",
        interpretation="Meta-label recall for the TAKE class.",
        applicability="event_outcome",
        layer="meta",
        label_space="meta",
    ),
    MetricSpec(
        name="{split}/meta/f1",
        location="evaluator",
        interpretation="Meta-label F1 for the TAKE class.",
        applicability="event_outcome",
        layer="meta",
        label_space="meta",
        notes="Primary checkpoint-selection metric in the current project pipeline.",
    ),
    MetricSpec(
        name="{split}/meta/accuracy",
        location="evaluator",
        interpretation="Meta-label accuracy over pass/take decisions.",
        applicability="event_outcome",
        layer="meta",
        label_space="meta",
    ),
    MetricSpec(
        name="{split}/meta/take_probability_mean",
        location="evaluator",
        interpretation="Mean predicted TAKE probability from the logistic meta-label model.",
        applicability="event_outcome",
        layer="meta",
        label_space="meta",
    ),
    MetricSpec(
        name="{split}/meta/take_probability_median",
        location="evaluator",
        interpretation="Median predicted TAKE probability from the logistic meta-label model.",
        applicability="event_outcome",
        layer="meta",
        label_space="meta",
    ),
    MetricSpec(
        name="{split}/meta/take_rate",
        location="evaluator",
        interpretation="Fraction of samples the meta model converts into TAKE decisions.",
        applicability="event_outcome",
        layer="meta",
        label_space="meta",
    ),
    MetricSpec(
        name="{split}/meta/truth_take_rate",
        location="evaluator",
        interpretation="Fraction of samples whose realized outcome supports TAKING the proposed trade.",
        applicability="event_outcome",
        layer="meta",
        label_space="meta",
    ),
    MetricSpec(
        name="{split}/meta_accept_threshold",
        location="evaluator aliases",
        interpretation="Flat alias of the meta accept threshold used for trade gating.",
        applicability="event_outcome",
        layer="decision",
        label_space="meta",
        primary_debug_metric=False,
        notes="Prefer {split}/decision/meta_accept_threshold or {split}/meta/accept_threshold in dashboards.",
    ),
    MetricSpec(
        name="{split}/trade_signal_count",
        location="evaluator aliases",
        interpretation="Flat alias for the number of acted trade signals after meta filtering.",
        applicability="event_outcome",
        layer="decision",
        label_space="trade",
        primary_debug_metric=False,
        notes="Prefer {split}/decision/trade_signal_count in dashboards.",
    ),
    MetricSpec(
        name="{split}/trade_signal_rate",
        location="evaluator aliases",
        interpretation="Flat alias for the acted trade-signal rate after meta filtering.",
        applicability="event_outcome",
        layer="decision",
        label_space="trade",
        primary_debug_metric=False,
        notes="Prefer {split}/decision/trade_signal_rate in dashboards.",
    ),
    MetricSpec(
        name="{split}/abstained_prediction_rate_pct",
        location="evaluator aliases",
        interpretation="Flat alias of the abstention rate after the meta decision layer.",
        applicability="event_outcome",
        layer="decision",
        label_space="trade",
        legacy=True,
        primary_debug_metric=False,
        notes="Prefer {split}/decision/abstained_prediction_rate_pct.",
    ),
    MetricSpec(
        name="{split}/acted_prediction_accuracy",
        location="evaluator aliases",
        interpretation="Flat alias of acted-only accuracy in canonical trade-label space.",
        applicability="event_outcome",
        layer="decision",
        label_space="trade",
        primary_debug_metric=False,
        notes="Prefer {split}/decision/acted_prediction_accuracy.",
    ),
    MetricSpec(
        name="{split}/directional_acted_accuracy",
        location="evaluator aliases",
        interpretation="Flat alias of acted-only accuracy restricted to directional truths.",
        applicability="event_outcome",
        layer="decision",
        label_space="trade",
        primary_debug_metric=False,
        notes="Prefer {split}/decision/directional_acted_accuracy.",
    ),
    MetricSpec(
        name="{split}/actionable_truth_rate_pct",
        location="evaluator aliases",
        interpretation="Flat alias of how often the canonical truth is a directional trade event.",
        applicability="event_outcome",
        layer="decision",
        label_space="trade",
        primary_debug_metric=False,
        notes="Prefer {split}/decision/actionable_truth_rate_pct.",
    ),
    MetricSpec(
        name="{split}/abstain_on_actionable_truth_pct",
        location="evaluator aliases",
        interpretation="Flat alias of abstention rate on rows whose canonical truth is actionable.",
        applicability="event_outcome",
        layer="decision",
        label_space="trade",
        primary_debug_metric=False,
        notes="Prefer {split}/decision/abstain_on_actionable_truth_pct.",
    ),
    MetricSpec(
        name="{split}/acted_on_exit_truth_pct",
        location="evaluator aliases",
        interpretation="Flat alias of false-action rate on canonical EXIT rows.",
        applicability="event_outcome",
        layer="decision",
        label_space="trade",
        primary_debug_metric=False,
        notes="Prefer {split}/decision/acted_on_exit_truth_pct.",
    ),
    MetricSpec(
        name="{split}/decision/meta_accept_threshold",
        location="evaluator",
        interpretation="Meta probability threshold used to turn side-model proposals into trade decisions.",
        applicability="event_outcome",
        layer="decision",
        label_space="meta",
    ),
    MetricSpec(
        name="{split}/decision/trade_signal_count",
        location="evaluator",
        interpretation="Count of non-EXIT trade decisions after meta filtering.",
        applicability="event_outcome",
        layer="decision",
        label_space="trade",
    ),
    MetricSpec(
        name="{split}/decision/trade_signal_rate",
        location="evaluator",
        interpretation="Fraction of samples that survive meta filtering and become trade signals.",
        applicability="event_outcome",
        layer="decision",
        label_space="trade",
    ),
    MetricSpec(
        name="{split}/decision/abstained_prediction_rate_pct",
        location="evaluator + paper aliases",
        interpretation="Percentage of samples converted into EXIT/no-trade after the meta decision layer.",
        applicability="event_outcome",
        layer="decision",
        label_space="trade",
    ),
    MetricSpec(
        name="{split}/decision/acted_prediction_accuracy",
        location="evaluator + paper aliases",
        interpretation="Accuracy restricted to rows where the final trade decision chose to act.",
        applicability="event_outcome",
        layer="decision",
        label_space="trade",
    ),
    MetricSpec(
        name="{split}/decision/directional_acted_accuracy",
        location="evaluator + paper aliases",
        interpretation="Accuracy on acted rows whose canonical truth is directional.",
        applicability="event_outcome",
        layer="decision",
        label_space="trade",
        notes="Preferred acted-only correctness metric across the current pipeline.",
    ),
    MetricSpec(
        name="{split}/decision/actionable_truth_rate_pct",
        location="evaluator + paper aliases",
        interpretation="Share of rows whose canonical event-outcome truth is directional rather than EXIT.",
        applicability="event_outcome",
        layer="decision",
        label_space="trade",
    ),
    MetricSpec(
        name="{split}/decision/abstain_on_actionable_truth_pct",
        location="evaluator + paper aliases",
        interpretation="How often the decision layer abstains even though the canonical truth was actionable.",
        applicability="event_outcome",
        layer="decision",
        label_space="trade",
    ),
    MetricSpec(
        name="{split}/decision/acted_on_exit_truth_pct",
        location="evaluator + paper aliases",
        interpretation="How often the decision layer acts on rows whose canonical truth was EXIT/no-trade.",
        applicability="event_outcome",
        layer="decision",
        label_space="trade",
    ),
    MetricSpec(
        name="{split}/execution/n_trade_signals_raw",
        location="evaluator + paper aliases",
        interpretation="Number of raw acted trade signals before overlap suppression.",
        applicability="event_outcome",
        layer="execution",
        label_space="trade",
    ),
    MetricSpec(
        name="{split}/execution/n_trade_signals_skipped_overlap",
        location="backtest -> evaluator aliases",
        interpretation="Count of raw signals dropped because another trade on the same ticker was already open.",
        applicability="event_outcome",
        layer="execution",
        label_space="trade",
    ),
    MetricSpec(
        name="{split}/execution/n_executed_trades",
        location="backtest -> evaluator aliases",
        interpretation="Number of actually executed non-overlapping trades.",
        applicability="event_outcome",
        layer="execution",
        label_space="trade",
        notes="Mirror of {split}/paper/n_executed_trades placed in the execution namespace.",
    ),
    MetricSpec(
        name="{split}/execution/share_time_active_pct",
        location="backtest -> evaluator aliases",
        interpretation="Share of the backtest horizon during which at least one trade was active.",
        applicability="event_outcome",
        layer="execution",
        label_space="trade",
        notes="Mirror of {split}/paper/share_time_active_pct placed in the execution namespace.",
    ),
    MetricSpec(
        name="{split}/execution/executed_trade_hit_rate_pct",
        location="backtest -> evaluator aliases",
        interpretation="Directional hit rate across executed trades only.",
        applicability="event_outcome",
        layer="execution",
        label_space="trade",
        notes="Mirror of {split}/paper/executed_trade_hit_rate_pct placed in the execution namespace.",
    ),
    MetricSpec(
        name="{split}/paper/annual_net_profit_loss_pct",
        location="backtest",
        interpretation="Annualized net portfolio return from executed trades.",
        applicability="event_outcome",
        layer="economics",
        label_space="trade",
    ),
    MetricSpec(
        name="{split}/paper/profitable_transactions_pct",
        location="backtest",
        interpretation="Percentage of executed trades with positive net return.",
        applicability="event_outcome",
        layer="economics",
        label_space="trade",
    ),
    MetricSpec(
        name="{split}/paper/accuracy_all_predictions",
        location="backtest",
        interpretation="Canonical trade-label accuracy over all rows after abstention.",
        applicability="event_outcome",
        layer="economics",
        label_space="trade",
        legacy=True,
        primary_debug_metric=False,
        notes="Not a primary learning metric; abstentions can make it look artificially poor.",
    ),
    MetricSpec(
        name="{split}/paper/acted_prediction_accuracy",
        location="backtest",
        interpretation="Acted-only accuracy in canonical trade-label space.",
        applicability="event_outcome",
        layer="economics",
        label_space="trade",
        primary_debug_metric=False,
        notes="Prefer the mirrored {split}/decision/acted_prediction_accuracy metric in dashboards.",
    ),
    MetricSpec(
        name="{split}/paper/directional_acted_accuracy",
        location="backtest",
        interpretation="Acted-only accuracy restricted to canonical directional truths.",
        applicability="event_outcome",
        layer="economics",
        label_space="trade",
        primary_debug_metric=False,
        notes="Prefer the mirrored {split}/decision/directional_acted_accuracy metric in dashboards.",
    ),
    MetricSpec(
        name="{split}/paper/actionable_truth_rate_pct",
        location="backtest",
        interpretation="Share of rows whose canonical truth is directional rather than EXIT.",
        applicability="event_outcome",
        layer="economics",
        label_space="trade",
        primary_debug_metric=False,
        notes="Prefer the mirrored {split}/decision/actionable_truth_rate_pct metric in dashboards.",
    ),
    MetricSpec(
        name="{split}/paper/abstained_prediction_rate_pct",
        location="backtest",
        interpretation="Percentage of rows the decision layer converted into EXIT/no-trade.",
        applicability="event_outcome",
        layer="economics",
        label_space="trade",
        primary_debug_metric=False,
        notes="Prefer the mirrored {split}/decision/abstained_prediction_rate_pct metric in dashboards.",
    ),
    MetricSpec(
        name="{split}/paper/abstain_on_actionable_truth_pct",
        location="backtest",
        interpretation="Abstention rate on rows whose canonical truth was actionable.",
        applicability="event_outcome",
        layer="economics",
        label_space="trade",
        primary_debug_metric=False,
        notes="Prefer the mirrored {split}/decision/abstain_on_actionable_truth_pct metric in dashboards.",
    ),
    MetricSpec(
        name="{split}/paper/acted_on_exit_truth_pct",
        location="backtest",
        interpretation="False-action rate on rows whose canonical truth was EXIT.",
        applicability="event_outcome",
        layer="economics",
        label_space="trade",
        primary_debug_metric=False,
        notes="Prefer the mirrored {split}/decision/acted_on_exit_truth_pct metric in dashboards.",
    ),
    MetricSpec(
        name="{split}/paper/sharpe_ratio_annualized",
        location="backtest",
        interpretation="Annualized Sharpe ratio of the daily portfolio-value series.",
        applicability="event_outcome",
        layer="economics",
        label_space="trade",
    ),
    MetricSpec(
        name="{split}/paper/max_drawdown_pct",
        location="backtest",
        interpretation="Maximum drawdown of the daily portfolio-value series.",
        applicability="event_outcome",
        layer="economics",
        label_space="trade",
    ),
    MetricSpec(
        name="{split}/paper/share_time_active_pct",
        location="backtest",
        interpretation="Share of the backtest horizon during which at least one trade was active.",
        applicability="event_outcome",
        layer="execution",
        label_space="trade",
    ),
    MetricSpec(
        name="{split}/paper/n_trade_signals_raw",
        location="backtest",
        interpretation="Number of raw acted trade signals before overlap suppression.",
        applicability="event_outcome",
        layer="execution",
        label_space="trade",
        primary_debug_metric=False,
        notes="Prefer the mirrored {split}/execution/n_trade_signals_raw metric in dashboards.",
    ),
    MetricSpec(
        name="{split}/paper/n_trade_signals_skipped_overlap",
        location="backtest",
        interpretation="Raw trade signals skipped because another same-ticker trade was still open.",
        applicability="event_outcome",
        layer="execution",
        label_space="trade",
        primary_debug_metric=False,
        notes="Prefer the mirrored {split}/execution/n_trade_signals_skipped_overlap metric in dashboards.",
    ),
    MetricSpec(
        name="{split}/paper/n_executed_trades",
        location="backtest",
        interpretation="Number of actually executed non-overlapping trades.",
        applicability="event_outcome",
        layer="execution",
        label_space="trade",
    ),
    MetricSpec(
        name="{split}/paper/executed_trade_hit_rate_pct",
        location="backtest",
        interpretation="Directional hit rate across executed trades only.",
        applicability="event_outcome",
        layer="execution",
        label_space="trade",
    ),
    MetricSpec(
        name="{split}/paper/executed_trade_gross_return_avg_pct",
        location="backtest",
        interpretation="Mean gross return per executed trade before transaction costs.",
        applicability="event_outcome",
        layer="economics",
        label_space="trade",
    ),
    MetricSpec(
        name="{split}/paper/executed_trade_net_return_avg_pct",
        location="backtest",
        interpretation="Mean net return per executed trade after transaction costs.",
        applicability="event_outcome",
        layer="economics",
        label_space="trade",
    ),
    MetricSpec(
        name="{split}/paper/executed_trade_gross_return_median_pct",
        location="backtest",
        interpretation="Median gross return per executed trade before transaction costs.",
        applicability="event_outcome",
        layer="economics",
        label_space="trade",
    ),
    MetricSpec(
        name="{split}/paper/executed_trade_net_return_median_pct",
        location="backtest",
        interpretation="Median net return per executed trade after transaction costs.",
        applicability="event_outcome",
        layer="economics",
        label_space="trade",
    ),
    MetricSpec(
        name="{split}/paper/executed_trade_gross_return_total_pct",
        location="backtest",
        interpretation="Total gross return across executed trades before transaction costs.",
        applicability="event_outcome",
        layer="economics",
        label_space="trade",
    ),
    MetricSpec(
        name="{split}/paper/executed_trade_net_return_total_pct",
        location="backtest",
        interpretation="Total net return across executed trades after transaction costs.",
        applicability="event_outcome",
        layer="economics",
        label_space="trade",
        notes="Useful companion to annualized return when comparing short debugging runs.",
    ),
    MetricSpec(
        name="{split}/paper/transaction_cost_total_pct",
        location="backtest",
        interpretation="Total transaction-cost drag across executed trades in percentage points.",
        applicability="event_outcome",
        layer="economics",
        label_space="trade",
    ),
    MetricSpec(
        name="{split}/paper/long_n_executed_trades",
        location="backtest",
        interpretation="Number of executed long trades.",
        applicability="event_outcome",
        layer="economics",
        label_space="trade",
    ),
    MetricSpec(
        name="{split}/paper/short_n_executed_trades",
        location="backtest",
        interpretation="Number of executed short trades.",
        applicability="event_outcome",
        layer="economics",
        label_space="trade",
    ),
    MetricSpec(
        name="{split}/paper/long_hit_rate_pct",
        location="backtest",
        interpretation="Directional hit rate across executed long trades.",
        applicability="event_outcome",
        layer="economics",
        label_space="trade",
    ),
    MetricSpec(
        name="{split}/paper/short_hit_rate_pct",
        location="backtest",
        interpretation="Directional hit rate across executed short trades.",
        applicability="event_outcome",
        layer="economics",
        label_space="trade",
    ),
    MetricSpec(
        name="{split}/paper/long_net_return_avg_pct",
        location="backtest",
        interpretation="Mean net return across executed long trades.",
        applicability="event_outcome",
        layer="economics",
        label_space="trade",
    ),
    MetricSpec(
        name="{split}/paper/short_net_return_avg_pct",
        location="backtest",
        interpretation="Mean net return across executed short trades.",
        applicability="event_outcome",
        layer="economics",
        label_space="trade",
    ),
    MetricSpec(
        name="{split}/paper/n_test_days",
        location="backtest",
        interpretation="Number of calendar days spanned by the portfolio-value series used for annualization.",
        applicability="event_outcome",
        layer="economics",
        label_space="run",
    ),
    MetricSpec(
        name="{split}/paper/tp",
        location="backtest",
        interpretation="True positives in canonical trade-label space for UP trades after abstention.",
        applicability="event_outcome",
        layer="economics",
        label_space="trade",
        primary_debug_metric=False,
    ),
    MetricSpec(
        name="{split}/paper/tn",
        location="backtest",
        interpretation="True negatives in canonical trade-label space for DOWN trades after abstention.",
        applicability="event_outcome",
        layer="economics",
        label_space="trade",
        primary_debug_metric=False,
    ),
    MetricSpec(
        name="{split}/paper/fp",
        location="backtest",
        interpretation="False positives in canonical trade-label space for UP trades after abstention.",
        applicability="event_outcome",
        layer="economics",
        label_space="trade",
        primary_debug_metric=False,
    ),
    MetricSpec(
        name="{split}/paper/fn",
        location="backtest",
        interpretation="False negatives in canonical trade-label space for UP trades after abstention.",
        applicability="event_outcome",
        layer="economics",
        label_space="trade",
        primary_debug_metric=False,
    ),
    MetricSpec(
        name="perf/confusion_matrix_normalized/{split}",
        location="wandb_logger",
        interpretation="Row-normalized confusion matrix table in the side-model label space.",
        applicability="both",
        layer="artifact",
        label_space="artifact",
        notes="The current project pipeline uses side labels here even when the stored truth is three-class event outcome.",
    ),
    MetricSpec(
        name="perf/profit_curve_over_trades/{split}",
        location="wandb_logger",
        interpretation="Per-trade cumulative net-profit curve table built from executed trades.",
        applicability="event_outcome",
        layer="artifact",
        label_space="artifact",
    ),
    MetricSpec(
        name="perf/per_ticker_table",
        location="wandb_logger",
        interpretation="Best-run per-ticker accuracy and trade profitability table.",
        applicability="event_outcome",
        layer="artifact",
        label_space="artifact",
        notes="Only logged for the best namespace to keep runs lightweight.",
    ),
)


DEBUG_DASHBOARD_CONTRACT: tuple[tuple[str, str, str], ...] = (
    ("Training", "train/loss", "Optimization loss on training minibatches."),
    ("Training", "val/loss", "Validation loss in the side-model label space."),
    ("Learning", "{split}/cls/accuracy", "Primary side-model accuracy before meta filtering."),
    ("Learning", "{split}/cls/f1_macro", "Primary balanced side-model metric before meta filtering."),
    ("Learning", "perf/confusion_matrix_normalized/{split}", "Normalized side-label confusion matrix by split."),
    ("Meta", "{split}/meta/f1", "Checkpoint-selection metric for the meta TAKE classifier."),
    ("Meta", "{split}/meta/take_rate", "How often the meta model allows a trade through."),
    ("Decision", "{split}/decision/meta_accept_threshold", "Meta decision threshold currently in force."),
    ("Decision", "{split}/decision/abstained_prediction_rate_pct", "How often the strategy abstains."),
    ("Decision", "{split}/decision/directional_acted_accuracy", "Acted-only correctness on directional truths."),
    ("Decision", "{split}/decision/abstain_on_actionable_truth_pct", "Missed trades on actionable truths."),
    ("Decision", "{split}/decision/acted_on_exit_truth_pct", "False actions on EXIT truths."),
    ("Execution", "{split}/execution/n_trade_signals_raw", "Raw acted signals before overlap suppression."),
    ("Execution", "{split}/execution/n_trade_signals_skipped_overlap", "Signals dropped due to same-ticker overlap."),
    ("Execution", "{split}/execution/n_executed_trades", "Executed non-overlapping trades."),
    ("Execution", "{split}/execution/share_time_active_pct", "Share of the backtest horizon with open exposure."),
    ("Economics", "{split}/paper/executed_trade_net_return_avg_pct", "Average net edge per executed trade."),
    ("Economics", "{split}/paper/executed_trade_net_return_total_pct", "Total net return across executed trades."),
    ("Economics", "{split}/paper/transaction_cost_total_pct", "Total transaction-cost drag."),
    ("Economics", "{split}/paper/annual_net_profit_loss_pct", "Annualized portfolio return."),
    ("Economics", "{split}/paper/sharpe_ratio_annualized", "Risk-adjusted performance."),
    ("Economics", "{split}/paper/max_drawdown_pct", "Worst drawdown in the paper portfolio."),
    ("Direction Split", "{split}/paper/long_n_executed_trades", "Executed long trades."),
    ("Direction Split", "{split}/paper/short_n_executed_trades", "Executed short trades."),
    ("Direction Split", "{split}/paper/long_hit_rate_pct", "Long-side hit rate."),
    ("Direction Split", "{split}/paper/short_hit_rate_pct", "Short-side hit rate."),
    ("Artifacts", "perf/profit_curve_over_trades/{split}", "Executed-trade profit curve table."),
    ("Artifacts", "perf/per_ticker_table", "Best-run per-ticker performance table."),
)


def metric_inventory_rows() -> List[dict]:
    return [
        {
            "name": spec.name,
            "location": spec.location,
            "interpretation": spec.interpretation,
            "applicability": spec.applicability,
            "layer": spec.layer,
            "label_space": spec.label_space,
            "legacy": int(spec.legacy),
            "primary_debug_metric": int(spec.primary_debug_metric),
            "notes": spec.notes,
        }
        for spec in METRIC_SPECS
    ]


def dashboard_contract_rows() -> List[dict]:
    return [
        {
            "section": section,
            "metric": metric,
            "notes": notes,
        }
        for section, metric, notes in DEBUG_DASHBOARD_CONTRACT
    ]


def metric_names_for_layer(layer: str) -> Iterable[str]:
    return (spec.name for spec in METRIC_SPECS if spec.layer == layer)
